### DISCUSSION TITLE
Change iFrameManager button colors

### DISCUSSION THREAD

**Discussion by jemmsuk** [orestbida/iframemanager#54] [Show and tell]
I wanted to change the button colors, one color for Youtube service and a different color for Google Maps service.

This is what I came up with in additional CSS that works for me, might be useful for someone else:

`/*iFrame Manager Button Colors*/

/*Youtube Button Color*/
div[data-service="youtube"] .cll .c-l-b {
  background: rgb(255 0 0 / 84%);
}

 /*Google Maps Button Color*/
div[data-service="googlemaps"] .cll .c-l-b {
  background: rgb(15 157 88 / 84%);
}
/*End iFrame Manager Button Colors */`

**Comment by orestbida** [comment]
I would recommend using the css-variables approach, as shown in the demo:

```css
div[data-service="youtube"] {
    --im-btn-bg: rgba(255, 45, 45, 0.85);
    --im-btn-hover-bg: rgba(255, 45, 45, 0.65);
    --im-link-color: #fa6363;
    --im-link-hover-color: #c54747;
    --im-btn-active-box-shadow: 0 0 0 4px rgba(250, 24, 24, 0.15);
    --im-overlay-bg: linear-gradient(14deg, rgba(250, 24, 24, 0.15) 0%, rgba(206,220,233,0.118) 100%)
}
```
